# .github/workflows/auto-merge-when-ready.yml
name: Auto Add to Merge Queue

on:
  pull_request:
    types: [labeled, synchronize]

jobs:
  auto-queue:
    if: github.event.pull_request.state == 'open'
    runs-on: ubuntu-latest

    steps:
      - name: Check required conditions
        uses: actions/github-script@v7
        id: check-conditions
        with:
          script: |
            const pr = context.payload.pull_request;

            const labelExists = pr.labels.some(label => label.name === 'merge-when-ready');
            if (!labelExists) {
              core.setOutput('should-merge', 'false');
              return;
            }

            // Check latest commit status for 'validate-pr'
            const checks = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: pr.head.sha
            });

            const sonarCheck = checks.data.check_runs.find(run => run.name === 'validate-pr');
            if (!sonarCheck || sonarCheck.conclusion !== 'success') {
              core.setOutput('should-merge', 'false');
              return;
            }

            core.setOutput('should-merge', 'true');

      - name: Add PR to merge queue
        if: steps.check-conditions.outputs.should-merge == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            await github.graphql(`
              mutation($pullRequestId: ID!) {
                addPullRequestToMergeQueue(input: { pullRequestId: $pullRequestId }) {
                  pullRequest {
                    id
                    number
                  }
                }
              }
            `, {
              pullRequestId: context.payload.pull_request.node_id
            });

