# .github/workflows/auto-merge-when-ready.yml
name: Auto Add to Merge Queue

on:
  pull_request:
    types: [labeled, synchronize]

jobs:
  auto-queue:
    if: github.event.pull_request.state == 'open'
    runs-on: ubuntu-latest

    steps:
      - name: Check required conditions
        uses: actions/github-script@v7
        id: check-conditions
        with:
          script: |
            const pr = context.payload.pull_request;

            const labelExists = pr.labels.some(label => label.name === 'merge-when-ready');
            if (!labelExists) {
              core.setOutput('should-merge', 'false');
              return;
            }

            // Check latest commit status for 'validate-pr'
            const checks = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: pr.head.sha
            });

            const sonarCheck = checks.data.check_runs.find(run => run.name === 'validate-pr');
            if (!sonarCheck || sonarCheck.conclusion !== 'success') {
              core.setOutput('should-merge', 'false');
              return;
            }

            core.setOutput('should-merge', 'true');
            core.setOutput('prId', pr.node_id);

      - name: Enqueue PR
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            await github.graphql(`
              mutation($prId: ID!) {
                enqueuePullRequest(input:{pullRequestId:$prId}) { clientMutationId }
              }`, { prId: '${{ steps.check.outputs.prId }}' });

      - name: 📬 Notify
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner, repo: context.repo.repo,
              issue_number: github.context.payload.pull_request?.number || github.context.payload.workflow_run.pull_requests[0].number,
              body: "✅ Enqueued via API — please check merge-group CI. If it doesn't start, enqueue manually."
            });

