name: Piperks Backend Deployment
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      BUILD_APP: 'backend'
      BUILD_STAGE: 'staging'
      AWS_EBS_PLATFORM: 'Node.js'
      AWS_EBS_APPLICATION: 'Piperks-backend'
      AWS_EBS_ENVIRONMENT: 'testing'
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Get environment variable from aws ssm
        uses: Bardavon-Health/actions-aws-ssm-params-to-env@v1.2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        with:
          ssm-path: /${{ env.BUILD_STAGE }}/${{ env.BUILD_APP }}/test
          prefix: null
          decryption: true
          
      - name: Output Bardavon Actions
        env:
          CNAME: ${{ env.AWS_DEFAULT_REGION }}
        run: | 
          echo "$CNAME"
          echo ${{ env.AWS_DEFAULT_REGION }}
          if [ ${{ env.AWS_DEFAULT_REGION }} = ap-southeast-1 ]; then
            echo "true"
          else
            echo "false"
          fi

      # - name: Parse and set environment variables
      #   run: |
      #     echo "${{ env.API_KEYS_JSON }}" > keys.json
      #     envs=$(jq -r 'to_entries | map("\(.key)=\(.value|tostring)") | join("\n")' keys.json)
      #     echo "$envs" >> $GITHUB_ENV

      # - name: Create .env file
      #   id: create-env
      #   uses: SpicyPizza/create-envfile@v2.0
      #   with:
      #     envkey_API_KEYS_JSON: ${{ env.API_KEYS_JSON }}
      #     envkey_API_KEYS: ${{ toJSON(env.API_KEYS_JSON) }}
      #     envkey_SANDBOX_MODE: false
      #     envkey_DEMO_MODE: false
      #     envkey_PLAYGROUND: false
      #     envkey_API_DOCS_PATH: /docs
      #     fail_on_empty: true
          
      # - name: Read .env file contents
      #   run: |
      #     echo "Contents of .env file:"
      #     cat .env

      # - name: Save .env file as artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: env-file
      #     path: .env
      
      - name: Install EB CLI using pip
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli

      - name: Initialize EB CLI
        run: |
          eb init ${{ env.AWS_EBS_APPLICATION }} --region ${{ env.AWS_DEFAULT_REGION }} --platform ${{ env.AWS_EBS_PLATFORM }}
          eb use ${{ env.AWS_EBS_ENVIRONMENT }}

      - name: Get Elastic Beanstalk blue environment name
        id: target-blue-env
        env:
          CNAME: ${{ env.AWS_DEFAULT_REGION }}
        run: |
          echo ${{ env.CNAME }}
          for ebs_env in $(eb list | awk '{print $1}'); do
            ebs_env_cname=$(eb status $ebs_env | grep "CNAME:" | awk '{print $2}')
            [ "$ebs_env_cname" = ${{ env.CNAME }} ] && blue_env_name="$ebs_env" >> $GITHUB_OUTPUT
          done
          
          if [ -n "$blue_env_name" ]; then
            echo "Blue environment found: $blue_env_name"
          else
            echo "Elastic beanstalk blue environment not found"
            exit 1
          fi

