name: Piperks Backend Deployment
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      BUILD_APP: 'backend'
      BUILD_STAGE: 'staging'
      AWS_EBS_PLATFORM: 'Node.js'
      AWS_EBS_APPLICATION: 'Piperks-backend'
      AWS_EBS_ENVIRONMENT: 'staging'
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Get environment variable from aws ssm
        uses: Bardavon-Health/actions-aws-ssm-params-to-env@v1.2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        with:
          ssm-path: /${{ env.BUILD_STAGE }}/${{ env.BUILD_APP }}/STAGING_ENV
          prefix: null
          decryption: true

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_API_KEYS_JSON: ${{ env.API_KEYS_JSON }}
          envkey_SANDBOX_MODE: false
          envkey_DEMO_MODE: false
          envkey_PLAYGROUND: false
          envkey_API_DOCS_PATH: /docs
          fail_on_empty: true

      - name: Convert API_KEYS_JSON to JSON string
        run: |
          API_KEYS_JSON=$(echo "${{ env.API_KEYS_JSON }}" | jq -c -r)
          echo "API_KEYS_JSON=${API_KEYS_JSON}" >> $GITHUB_ENV
